version: "3" 
services:
  postgres:
    container_name: postgres
    image: postgres:12.4-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: my_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    volumes:
        - data-volume:/var/lib/postgresql
  redis:
    container_name: redis
    image: redis:4-alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
        - data-volume:/data
volumes:
  data-volume:
  mysql-volume-global-admin: